# Generated by Django 2.0.5 on 2018-07-09 16:32

import cuser.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cuser', '0003_auto_20180709_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('cuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('cuser.cuser', models.Model),
            managers=[
                ('objects', cuser.models.CUserManager()),
            ],
        ),
    ]
